name: X Posting Bot

on:
  schedule:
    # 9時から22時まで毎時実行（日本時間）
    - cron: '0 0-13 * * *'  # UTC 0-13時 = JST 9-22時
    # 注意: GitHub ActionsはUTC時間で動作します
  workflow_dispatch:  # 手動実行も可能

# ワークフロー全体の権限設定
permissions:
  contents: write
  actions: read

jobs:
  post:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run X Posting Bot
      env:
        # 環境変数でAPI認証情報を設定（GitHub Secretsから取得）
        X_API_KEY: ${{ secrets.X_API_KEY }}
        X_API_SECRET: ${{ secrets.X_API_SECRET }}
        X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
        X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
      run: |
        python x_posting_bot_advanced.py
        
    - name: Commit and push posting history
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add posting_history.json x_bot.log
        git diff --quiet && git diff --staged --quiet || git commit -m "Update posting history - $(date)"
        git push 